added g2psandbox superset chart
fynarfin/fineract-env pull request #30
Opened 2023-02-06 12:19 UTC by somanath21

Created g2psandbox superset chart for fineract

2023-02-06 12:48 UTC, fynmanoj requested changes

2023-02-06 12:48 UTC, fynmanoj commented on helm/fineract/values.yaml
> -      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
we dont need to delete this

2023-02-06 12:48 UTC, fynmanoj commented on helm/g2pconnect-superset/values.yaml
> +    preStopScript: 'mysql -h fineract-mysql -u root -p4ET6ywqlGt fineract_tenants -e "INSERT IGNORE INTO tenant_server_connections (id, schema_server, schema_name, schema_server_port, schema_username
INSERT IGNORE is missing here: `"INSERT INTO tenants (id, identifier, name, timezone_id, country_id, joined_date, created_date, lastmodified_date, oltp_id, report_id) VALUES (2, \"gorilla\", \"test2\", \"Asia/Kolkata\", NULL, NULL, NULL, NULL, 2, 2)";'`

2023-02-06 13:02 UTC, somanath21 commented on helm/fineract/values.yaml
> -      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
I have re-added it in next commit

2023-02-06 13:09 UTC, somanath21 commented on helm/fineract/values.yaml
> -      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
added in new commit

2023-02-07 05:48 UTC, fynmanoj commented on helm/g2pconnect-superset/values.yaml
> +    preStopScript: 'mysql -h fineract-mysql -u root -p4ET6ywqlGt fineract_tenants -e "INSERT IGNORE INTO tenant_server_connections (id, schema_server, schema_name, schema_server_port, schema_username
can you update this?

2023-02-07 08:11 UTC, somanath21 commented on helm/g2pconnect-superset/values.yaml
> +    preStopScript: 'mysql -h fineract-mysql -u root -p4ET6ywqlGt fineract_tenants -e "INSERT IGNORE INTO tenant_server_connections (id, schema_server, schema_name, schema_server_port, schema_username
Updated in New commit

2023-02-07 13:05 UTC, fynmanoj approved these changes

2023-02-07 13:05 UTC, merged